# Use an existing docker image as base
FROM node:alpine

#Work directory
WORKDIR /usr/app

# Download and install dependencies
COPY ./package.json ./
RUN npm install
COPY ./ ./

# Tell the image what to do when it stats as a container
CMD ["npm", "run", "start"]